/**
 * «Obras participantes»: which artworks of the catalogue were in this show
 * (RF-505, RF-513).
 *
 * The natural reading of an exhibition record, and it needs no new table: the
 * bridge `artwork_exhibitions` is already there, already read from the other end
 * by the artwork's own history, and already carries the number each piece had in
 * the show's catalogue.
 *
 * **This block only reads, and that is not a shortcoming of the delivery.** A
 * participation is a fact about an ARTWORK — «esta obra estuvo en esta muestra,
 * con el número 12 bis» — and it is added from the artwork's record, where the
 * cataloger has the piece in front of her and its research status to keep
 * coherent. Adding it from here would be the same row written from two screens
 * with two different sets of rules, and one of them would be the one that lets a
 * participation into a history declared «investigado, sin resultados». So: read,
 * count, and link to each record, which is where writing lives.
 *
 * Pure, like every decision of this feature.
 */

import { displayDate } from '../../lib/dates'
import { displayTitle } from '../../lib/title'
import type { ArtistFund, ArtworkExhibition } from '../../lib/types'
import { ARTIST_LABEL } from '../../lib/types'

/**
 * The artwork as this block links to it: enough to recognise it and no more.
 *
 * Not the measurements, not the photographs, not the documentary state — the
 * record is one tap away and it has everything. Same shape and same reasoning as
 * `ArtworkRef` in the documentary rows, and written out separately because the
 * query is this feature's own.
 */
export interface ParticipantArtworkRef {
  catalog_id: string
  title: string
  artist: ArtistFund
  /** Generated by the database from the structured fields (ADR-004). Read-only. */
  execution_date: string
  active: boolean
}

/** One row of the block: the bridge row plus the artwork it names. */
export interface ParticipantRow extends ArtworkExhibition {
  /**
   * Null when the artwork behind a visible participation cannot be read. It
   * should not happen — the select policy of `artwork_exhibitions` demands the
   * artwork exist — but a row that arrives without it is said out loud rather
   * than painted as a blank line.
   */
  artwork: ParticipantArtworkRef | null
}

/**
 * The columns of the block. Written out because a TypeScript type does not exist
 * at run time, and held to `ParticipantRow` by a test: a field the query forgets
 * arrives as `undefined` with the type promising a value.
 */
export const PARTICIPANT_COLUMNS =
  'id, catalog_id, exhibition_id, catalogue_number, note, active, ' +
  'artwork:artworks(catalog_id, title, artist, execution_date, active)'

/**
 * The order of the block: **by the number the piece carried in the show's
 * catalogue**, and by identifier for whatever has none.
 *
 * Not by `catalog_id`, which is the order of the catalogue raisonné and has
 * nothing to do with this show. The number in the exhibition catalogue IS the
 * order of the exhibition — it is the order of the walls, printed on the page the
 * cataloger is holding — so reading the block down its numbers is reading the
 * show. Comparing those numbers as text would put «12 bis» before «2», which is
 * why they are compared numerically first and by the rest of the string after:
 * «12», «12 bis», «13».
 *
 * Rows with no number go LAST and not first: an empty number is a datum nobody
 * has copied yet, and sorting it to the head of the show would make it look like
 * piece number one.
 */
export function sortParticipants(rows: readonly ParticipantRow[]): ParticipantRow[] {
  return rows.slice().sort((a, b) => {
    const na = catalogueNumberKey(a.catalogue_number)
    const nb = catalogueNumberKey(b.catalogue_number)
    if (na.number !== nb.number) {
      if (na.number === null) return 1
      if (nb.number === null) return -1
      return na.number - nb.number
    }
    return (
      na.rest.localeCompare(nb.rest, 'es', { sensitivity: 'base' }) ||
      a.catalog_id.localeCompare(b.catalog_id, 'es') ||
      a.id.localeCompare(b.id)
    )
  })
}

/** `12 bis` → `{ number: 12, rest: 'bis' }`; `s/n` → `{ number: null, rest: 's/n' }`. */
function catalogueNumberKey(text: string): { number: number | null; rest: string } {
  const clean = text.trim()
  const match = /^(\d+)\s*(.*)$/.exec(clean)
  if (!match) return { number: null, rest: clean }
  return { number: Number(match[1]), rest: (match[2] ?? '').trim() }
}

/** One row of the block, ready to paint. */
export interface ParticipantEntry {
  /** The bridge row's identifier. Stable key of the list. */
  id: string
  /** The code of the artwork, which is the ONLY link to its record (RF-604). */
  catalogId: string
  /** The title, never a gap: an untitled artwork says so. */
  title: string
  /** `Rotili · 1985`. What tells two similar pieces apart at a glance. */
  subtitle: string
  /** `Nº 12 bis en el catálogo`, or null when saying it would invent a gap. */
  catalogueNumber: string | null
  /** The note of THIS participation: «prestada por la familia; sin marco». */
  note: string
  /** Something in this row is in the trash, and it says which. Null when nothing is. */
  retirementNotice: string | null
}

/**
 * What each row of the block says.
 *
 * `catalogueNumber` is null when there is no number AND nothing to be missing:
 * saying «sin número de catálogo registrado» under a show that consta sin
 * catálogo would invent a gap, so this block only says it when the caller says
 * the show had one. That is the same rule `catalogueNumberText` applies inside the
 * artwork's record, decided here from the other end because here the show is one
 * and the artworks are many.
 */
export function participantEntry(
  row: ParticipantRow,
  options: { cataloguePublished: boolean },
): ParticipantEntry {
  const number = row.catalogue_number.trim()
  return {
    id: row.id,
    catalogId: row.catalog_id,
    title: row.artwork === null ? 'Obra no disponible' : displayTitle(row.artwork.title),
    subtitle:
      row.artwork === null
        ? 'La ficha de esta obra no se puede leer con tu sesión'
        : `${ARTIST_LABEL[row.artwork.artist]} · ${displayDate(row.artwork.execution_date)}`,
    catalogueNumber:
      number !== ''
        ? `Nº ${number} en el catálogo`
        : options.cataloguePublished
          ? 'Sin número de catálogo registrado'
          : null,
    note: row.note.trim(),
    retirementNotice: participantRetirementNotice(row),
  }
}

/**
 * That what is being read is in the trash, said out loud.
 *
 * Two different things can be retired and they mean opposite things, so they do
 * not share a sentence: the PARTICIPATION in the trash means this artwork was
 * taken out of this show's list, and the ARTWORK in the trash means the piece
 * itself is withdrawn from the catalogue while its participation stands. Grey
 * that does not say which is decoration.
 *
 * The participation wins when both are retired: it is the row this line is about,
 * and two notices on one row of a phone is one too many — the same choice
 * `retirementNotice` makes in the artwork's record.
 */
function participantRetirementNotice(row: ParticipantRow): string | null {
  if (!row.active) {
    return 'Esta participación está retirada. Se recupera desde la ficha de la obra.'
  }
  if (row.artwork !== null && !row.artwork.active) {
    return 'La obra está retirada del catálogo.'
  }
  return null
}

/**
 * The rows of the block, in order and ready to paint.
 *
 * **Retired participations are NOT dropped**, unlike the artwork's own history,
 * which shows only what it holds today. From this end the question is different:
 * this is the list of everything the catalogue knows about who was in the show,
 * and a row silently missing from it is how somebody concludes that a piece was
 * never there. It is shown, greyed out, and it says why.
 */
export function participantEntries(
  rows: readonly ParticipantRow[],
  options: { cataloguePublished: boolean },
): ParticipantEntry[] {
  return sortParticipants(rows).map((row) => participantEntry(row, options))
}

/** How many artworks hold this exhibition up, counting only live participations. */
export function activeParticipantCount(rows: readonly ParticipantRow[]): number {
  return rows.filter((row) => row.active).length
}

/** `3 obras`, `1 obra`. The empty case is a sentence, never a zero. */
export function participantCountText(count: number): string {
  const rows = Math.max(0, Math.trunc(count))
  return rows === 1 ? '1 obra' : `${rows} obras`
}

/**
 * What goes where the rows would go, or null when there are rows to paint
 * (RF-304).
 *
 * The empty case is the one that matters, and it is «sin revisar» no es «no» read
 * from the other end. An exhibition with no artworks of the catalogue in it does
 * NOT mean the show had none: it means nobody has yet linked them, and the
 * linking happens one artwork at a time from each record, often years after the
 * show was registered from a press cutting. Printing «ninguna obra participó»
 * would answer a question nobody has asked, about somebody's unstarted afternoon
 * in an archive.
 *
 * While the query is in the air it says so, and after it failed it says nothing —
 * the error has its own line, and «todavía no hay ninguna» over a failed query is
 * the screen asserting what it does not know.
 */
export function participantsNotice(state: {
  loading: boolean
  error: string | null
  count: number
}): string | null {
  if (state.error !== null) return null
  if (state.loading) return 'Cargando las obras de esta exposición…'
  if (state.count > 0) return null
  return (
    'Ninguna obra del catálogo consta todavía en esta exposición. No quiere decir que no se ' +
    'expusiera ninguna: la participación se registra desde la ficha de cada obra, en su bloque ' +
    '«Historial expositivo», y aquí solo se lee.'
  )
}

/**
 * The thumbnails to ask for, given the rows (RF-505: the block carries a
 * thumbnail).
 *
 * Only the artworks that are actually painted, deduplicated: the same artwork can
 * hold two participations in one show — a live one and one that was retired — and
 * signing its thumbnail twice would spend a request on nothing.
 *
 * A separate function because the list of identifiers is what the query needs and
 * the query is not pure. Empty in, empty out: no rows must produce no request at
 * all, which is what keeps a show with no artworks from asking the storage service
 * to sign nothing.
 */
export function thumbnailCatalogIds(rows: readonly ParticipantRow[]): string[] {
  const seen = new Set<string>()
  for (const row of rows) seen.add(row.catalog_id)
  return [...seen].sort((a, b) => a.localeCompare(b, 'es'))
}
