/**
 * Enlazar un documento que YA está en el archivo con esta obra (RF-516, RF-517).
 *
 * **This is the act the bridge table exists for, and it is not a variant of
 * uploading.** A press cutting about a joint show mentions three artworks: with
 * v11's single foreign key that meant three documents and three copies of the same
 * PDF, which is the mistake `artwork_documents` was created to prevent. So the
 * catalogue holds ONE document and three links, and the screen has to make the
 * difference visible — otherwise the cataloger uploads the scan again from the
 * second artwork, and by the third nobody knows which of the three rows is the
 * real one.
 *
 * A document already in the archive is therefore LISTED and marked, never hidden:
 * the whole point is that she recognises it and links it instead of uploading it.
 *
 * Pure and free of React: what gets offered, what gets marked, what gets refused
 * and why is verified by the battery, which cannot open a component.
 */

import type { ResearchStatus } from '../../../lib/types'
import { fuzzyRankBy } from '../../../lib/vocabulary'
import { displayStructuredDate, fileSizeText } from '../documentaryFormat'
import type { DocumentLinkRow, MasterRef } from '../documentaryRows'

/**
 * The documents on offer in the chooser, as PostgREST wants them.
 *
 * Written out by hand because a TypeScript type does not exist at run time — the
 * same reason `documentaryRows.ts` keeps its column lists — and held to the
 * interface below by a test: a field the query forgets arrives as `undefined` with
 * the type promising a value.
 *
 * It is deliberately NARROWER than `DOCUMENT_LINK_COLUMNS`: a chooser needs to
 * identify a document, not to paint it. The note, the archive series and the place
 * of the paper are not read, because they do not tell two cuttings apart on a
 * phone and each of them is a join.
 */
export const DOCUMENT_OPTION_COLUMNS =
  'id, archive_code, title, artist_fund, document_type_id, start_year, end_year, ' +
  'approximate_date, unconfirmed_date, date_note, date_text, file_path, file_size_bytes, ' +
  'mime_type, active, document_type:document_types(id, name, active)'

/** One document of the archive as the chooser reads it. */
export interface DocumentOption {
  id: string
  archive_code: string | null
  title: string
  start_year: number | null
  end_year: number | null
  approximate_date: boolean
  unconfirmed_date: boolean
  date_note: string
  /** Generated by the database (ADR-004). */
  date_text: string
  file_path: string | null
  file_size_bytes: number | null
  mime_type: string | null
  active: boolean
  document_type: MasterRef | null
}

/**
 * What the cataloger reads on a row of the chooser, which is ALSO what the search
 * matches against.
 *
 * One string for both, and not a nice label plus a hidden search key: a list whose
 * rows match text they do not show looks arbitrary, and `SearchableCheckList`
 * already wrote that rule down.
 *
 * The signature is first because it is what is written on the folder and what gets
 * typed when it is known; the date is in because ten press cuttings are described
 * identically and the year is what tells them apart; the kind is in because
 * «Carta» and «Cartel» are different things with similar titles.
 */
export function documentOptionText(option: DocumentOption): string {
  const code = (option.archive_code ?? '').trim()
  const kind = option.document_type?.name.trim() ?? 'Tipo sin clasificar'
  return [code, option.title.trim(), kind, displayStructuredDate(option)]
    .filter((part) => part !== '')
    .join(' · ')
}

/**
 * Whether the document carries a scan, said in the chooser.
 *
 * It is the datum that decides whether linking is enough or whether the paper has
 * to be found and scanned, so it is on the row and not one tap deeper. There is no
 * `digitized` column: the answer is the path (RF-408).
 */
export function documentOptionFileText(option: DocumentOption): string {
  if (option.file_path === null || option.file_path.trim() === '') return 'Sin digitalizar'
  const weight = fileSizeText(option.file_size_bytes)
  return weight === null ? 'Digitalizado' : `Digitalizado · ${weight}`
}

/** One row of the chooser. */
export interface DocumentChoice {
  option: DocumentOption
  /** `documentOptionText`, ready to paint. */
  text: string
  /** Where the typed letters landed in `text`, for the emphasis. */
  indices: number[]
  /**
   * This artwork is already linked to that document. The row is still LISTED —
   * hiding it would make the chooser look as if the document were not in the
   * archive and invite uploading a second copy of the same PDF — but it cannot be
   * chosen again.
   */
  alreadyLinked: boolean
  /** Two words under the title: whether there is a file, or that it is already here. */
  fileText: string
}

/** The documents this artwork is already linked to, retired links included. */
export function linkedDocumentIds(rows: readonly DocumentLinkRow[]): Set<string> {
  return new Set(rows.map((row) => row.document_id))
}

/**
 * The documents to offer, best match first.
 *
 * Retired documents are DROPPED and not marked: this is a list to choose from, and
 * offering something the archive has withdrawn would put it back into use through
 * the back door. That is the opposite of the rule that governs a document already
 * linked from a live row, which is shown precisely because hiding it would lose a
 * name — a chooser and a record are not the same screen.
 *
 * The whole archive is ranked and nothing is cut off here: how many rows fit is a
 * decision of the sheet, and a limit buried in a pure function is a document that
 * cannot be found with no explanation on screen.
 */
export function rankDocumentOptions(
  options: readonly DocumentOption[],
  query: string,
  linked: ReadonlySet<string>,
): DocumentChoice[] {
  const offered = options.filter((option) => option.active)
  return fuzzyRankBy(offered, documentOptionText, query).map(({ item, indices }) => ({
    option: item,
    text: documentOptionText(item),
    indices,
    alreadyLinked: linked.has(item.id),
    fileText: linked.has(item.id)
      ? 'Ya está enlazado con esta obra'
      : documentOptionFileText(item),
  }))
}

/**
 * What the chooser says instead of an empty list, which it never is (RF-304).
 *
 * Three cases, and confusing them wastes an afternoon: the archive is empty, it
 * has documents and none matches, or everything that matches is already linked
 * here. The first two both have to point at the OTHER button — the one that
 * uploads — because a cataloger who types the title of the letter she is holding,
 * finds nothing and is told only «no hay resultados» concludes that the search is
 * broken instead of that the document is not in the archive yet.
 */
export function noDocumentOptionsText(total: number, query: string): string {
  if (total === 0) {
    return (
      'El archivo todavía no tiene ningún documento. Si tienes el papel o su escaneo delante, ' +
      'súbelo con «Subir un documento del archivo»: queda en el archivo y enlazado con esta obra.'
    )
  }
  const typed = query.trim()
  const about = typed === '' ? '' : ` con «${typed}»`
  return (
    `Ningún documento del archivo coincide${about}. Aquí solo se enlaza con lo que ya está en el ` +
    'archivo; si el documento no está todavía, súbelo con «Subir un documento del archivo».'
  )
}

/**
 * Why the whole chooser is off, or null when it is not.
 *
 * Two reasons, and neither of them is «no hay permiso»: the control is explained
 * and not hidden, because a missing button reads as a missing permission.
 */
export function allLinkedText(choices: readonly DocumentChoice[]): string | null {
  if (choices.length === 0) return null
  if (choices.some((choice) => !choice.alreadyLinked)) return null
  return (
    'Todos los documentos que coinciden están ya enlazados con esta obra. Si el que buscas no ' +
    'está en el archivo, súbelo con «Subir un documento del archivo».'
  )
}

/** The arguments of `document_artwork`, named as the function declares them. */
export interface DocumentLinkArgs {
  p_catalog_id: string
  p_document_id: string
  p_note: string
}

/**
 * The arguments of the `document_artwork` RPC — which is called instead of a plain
 * insert, and not for convenience.
 *
 * `artwork_documents_unique` covers RETIRED links too (RF-517), so an insert of a
 * pair that is in the trash crashes into the index and an «Añadir» turns into a
 * uniqueness violation nobody can read. The function finds that row and restores
 * it, which is exactly what adding it again means.
 *
 * A blank note is sent blank on purpose: the function keeps whatever is already
 * stored when what arrives is blank — «lo que no se manda no se borra» — so
 * re-adding a link from a form that opens empty cannot wipe the sentence somebody
 * researched about this artwork.
 */
export function documentLinkArgs(
  catalogId: string,
  documentId: string,
  note: string,
): DocumentLinkArgs {
  return {
    p_catalog_id: catalogId,
    p_document_id: documentId,
    p_note: note.trim(),
  }
}

/**
 * Why nothing can be linked right now, before asking the database (RF-218).
 *
 * `tg_artwork_document_status_coherent` refuses it and says so in Spanish — read
 * from the base: «La documentación de la obra AR-0001 consta investigada sin
 * resultado y este vínculo la contradice» — and that refusal is shown verbatim
 * when it happens. But a control that is going to be refused should say so BEFORE
 * it is pressed: the cataloger is standing up, and a round trip to be told no is
 * worse than a disabled button that explains itself. It also teaches that the two
 * things are connected, which the refusal alone does not.
 *
 * The wording follows the database's own hint and is not a second version of the
 * rule: change the state of the research first.
 */
export function linkBlockedReason(status: ResearchStatus | null): string | null {
  if (status !== 'NONE_FOUND') return null
  return (
    'La documentación consta «Investigado, sin resultados»: ponla en «Investigación en curso» o «Investigación completa».'
  )
}

/**
 * The two-tap confirmation of taking a document off the record, which has to say
 * exactly what disappears and what does not.
 *
 * Three things, and the second and third are the ones nobody expects:
 *
 *   · the link goes to the trash (RF-517, RF-901) — nothing is ever deleted, and
 *     adding it again restores this very row with its note;
 *   · **the document stays in the archive**, with its file, shared with every
 *     other artwork and exhibition that links to it. This is the whole reason the
 *     bridge table exists, and a cataloger who believes she is about to destroy a
 *     scanned expediente will leave a wrong link in the catalogue instead;
 *   · the file is not touched. It never is.
 */
export function retireLinkConfirmText(view: {
  title: string
  file: { bytes: number | null } | null
}): string {
  const title = view.title.trim()
  const named = title === '' ? 'este documento' : `«${title}»`
  const scanned =
    view.file === null
      ? ''
      : ' El fichero escaneado tampoco se toca: los originales del archivo no se borran nunca.'
  return (
    `${named} deja de constar en la documentación de esta obra. El documento sigue en el archivo ` +
    `y lo siguen viendo las demás obras y exposiciones enlazadas con él.${scanned} El vínculo va ` +
    'a la papelera y se puede volver a añadir.'
  )
}

/**
 * How the two acts differ, said once above the two buttons.
 *
 * It is the sentence this screen exists for. Without it the two buttons look like
 * a long way and a short way of doing the same thing, and the cataloger takes the
 * one that is on top — which for the second artwork of a press cutting means a
 * second copy of the PDF in the store and a second document in the archive, and
 * from then on two rows that have to be reconciled by hand.
 */
export const TWO_ACTS_TEXT =
  'Un documento se guarda una sola vez y cuelga de varias obras. Súbelo si todavía no está en el archivo.'
