/**
 * What each documentary block asks the database for, and what it does with the
 * answer.
 *
 * One shape and one column list per area, written out as strings because a
 * TypeScript type does not exist at run time — the same reason `artworkImages.ts`
 * and `photoDetails.ts` keep theirs. Whatever an interface here declares, its
 * `*_COLUMNS` constant has to select: a field the query forgets arrives as
 * `undefined` with the type promising a value, which is the bug the corners of a
 * photograph already cost this project once.
 *
 * **Retired master rows are NOT filtered out.** The bridge rows are (`active`),
 * because a retired citation is in the trash and the record does not show it;
 * but the reference, the venue, the party or the document type behind an active
 * row is loaded whatever its state, for the reason `usePhysicalPlaces` gives:
 * hiding it would leave a blank where a name used to be, and that is the one
 * thing this application does not do. Whoever paints a retired name greys it
 * out; nobody removes it.
 *
 * The ORDER of four of the five blocks is decided here and not in the query, and
 * it is not a preference: PostgREST cannot order a parent by a column of an
 * embedded row, and the order of these lists is a column of the embedded row —
 * the year of the reference, the opening date of the show. Sorting in the client
 * also makes it pure, which is the only way it gets verified: the battery runs
 * in node.
 */

import type {
  ArchiveDocument,
  ArtistFund,
  ArtworkBibliography,
  ArtworkDocument,
  ArtworkDocumentary,
  ArtworkExhibition,
  ArtworkRelationship,
  ArtworkRelationshipType,
  BibliographyEntry,
  Exhibition,
  ExhibitionDocument,
  ExhibitionVenue,
  ProvenanceEvent,
} from '../../lib/types'
import { exhibitionOrderKey, type PartyRef } from './documentaryFormat'

export type { PartyRef }

/** An entry of a vocabulary table, as these queries embed it. */
export interface MasterRef {
  id: string
  name: string
  active: boolean
}

/** A node of the archival classification tree, as the documents query embeds it. */
export interface ArchiveSeriesRef extends MasterRef {
  parent_id: string | null
}

/**
 * The other artwork of a relationship, as the record links to it (RF-305).
 *
 * Enough to draw a link and no more: the code, the title, whose it is and when
 * it was made. Not the measurements, not the photographs — the related record is
 * one tap away and it has them all.
 */
export interface ArtworkRef {
  catalog_id: string
  title: string
  artist: ArtistFund
  /** Generated by the database from the structured fields. Read-only. */
  execution_date: string
  active: boolean
}

const PARTY_FIELDS = 'id, party_type, name, locality, country, active'
// `contact` is deliberately absent from PARTY_FIELDS: see PartyRef.

// ── Provenance (RF-509) ──────────────────────────────────────

/** One link of the chain, with the party it names resolved. */
export interface ProvenanceEventRow extends ProvenanceEvent {
  /** Null when the link names its party in `party_note` instead, which is legitimate. */
  party: PartyRef | null
}

export const PROVENANCE_COLUMNS =
  'id, catalog_id, position, party_id, party_note, capacity, acquisition, ' +
  'start_year, end_year, approximate_date, unconfirmed_date, date_note, date_text, ' +
  `note, active, party:parties(${PARTY_FIELDS})`

/**
 * The chain in the order the cataloger arranged it (`position`), which is
 * MANUAL and not derived from the years: half the links of a catalogue raisonné
 * have no known date, and an order derived from nulls is not an order.
 *
 * The identifier only breaks ties, so two links never swap places on their own
 * between two loads of the same record.
 */
export function sortProvenance(rows: readonly ProvenanceEventRow[]): ProvenanceEventRow[] {
  return rows.slice().sort((a, b) => a.position - b.position || a.id.localeCompare(b.id))
}

// ── Bibliography (RF-504) ────────────────────────────────────

/** A reference with its publication type resolved. */
export interface ReferenceRow extends BibliographyEntry {
  publication_type: MasterRef | null
}

/** The citation of this artwork in a reference: the bridge row plus the reference. */
export interface CitationRow extends ArtworkBibliography {
  /** Null only when the Reader cannot see a retired reference the bridge still points at. */
  reference: ReferenceRow | null
}

export const CITATION_COLUMNS =
  'id, catalog_id, bibliography_id, pages, note, active, ' +
  'reference:bibliography(id, bibtex_key, authors, editors, title, container_title, ' +
  'publication_type_id, year, publisher, place, note, active, ' +
  'publication_type:publication_types(id, name, active))'

/**
 * Bibliography in chronological order, oldest first, with the undated last.
 *
 * A null year is «s.f.», which in bibliography is a datum and not a hole — but
 * it is not a date either, so it cannot take a place in the timeline. It goes at
 * the end, where the reader finds it, instead of at the top pretending to be the
 * earliest publication.
 *
 * Ties break by author and then title, with es-ES collation: the database's
 * default collation can sort «Álvarez» past the z, and it belongs with the a's.
 */
export function sortCitations(rows: readonly CitationRow[]): CitationRow[] {
  return rows.slice().sort((a, b) => {
    const ya = a.reference?.year ?? null
    const yb = b.reference?.year ?? null
    if (ya !== yb) {
      if (ya == null) return 1
      if (yb == null) return -1
      return ya - yb
    }
    return (
      compareText(a.reference?.authors ?? '', b.reference?.authors ?? '') ||
      compareText(a.reference?.title ?? '', b.reference?.title ?? '') ||
      a.id.localeCompare(b.id)
    )
  })
}

// ── Exhibition history (RF-501, RF-502) ──────────────────────

/** A venue with the institution behind it, when there is one. */
export interface VenueRow extends ExhibitionVenue {
  party: PartyRef | null
}

/** An exhibition with its venue resolved. */
export interface ExhibitionRow extends Exhibition {
  /** Null when the venue is only on record as free text in `venue_note`. */
  venue: VenueRow | null
}

/** The participation of this artwork in a show: the bridge row plus the show. */
export interface ParticipationRow extends ArtworkExhibition {
  exhibition: ExhibitionRow | null
}

export const PARTICIPATION_COLUMNS =
  'id, catalog_id, exhibition_id, catalogue_number, note, active, ' +
  'exhibition:exhibitions(id, title, exhibition_type, venue_id, venue_note, year, ' +
  'start_date, end_date, date_note, catalogue_published, catalogue_reference_id, note, active, ' +
  `venue:exhibition_venues(id, name, locality, country, party_id, note, active, party:parties(${PARTY_FIELDS})))`

/**
 * The exhibition history in ascending chronological order (RF-502), by the same
 * key the database indexes: the opening date, or the first of January of the
 * bare year.
 *
 * A show with no date at all cannot exist — the table checks it — and if one
 * arrives anyway it goes last and not first, where an empty key would have put
 * it at the head of the artist's career.
 */
export function sortParticipations(rows: readonly ParticipationRow[]): ParticipationRow[] {
  return rows.slice().sort((a, b) => {
    const ka = a.exhibition ? exhibitionOrderKey(a.exhibition) : null
    const kb = b.exhibition ? exhibitionOrderKey(b.exhibition) : null
    if (ka !== kb) {
      if (ka == null) return 1
      if (kb == null) return -1
      return ka < kb ? -1 : 1
    }
    return (
      compareText(a.exhibition?.title ?? '', b.exhibition?.title ?? '') || a.id.localeCompare(b.id)
    )
  })
}

// ── Archive documentation (RF-515, RF-516) ───────────────────

/** A document of the archive with its type and its place in the classification tree. */
export interface DocumentRow extends ArchiveDocument {
  document_type: MasterRef | null
  archive_series: ArchiveSeriesRef | null
}

/** The link between this artwork and a document: the bridge row plus the document. */
export interface DocumentLinkRow extends ArtworkDocument {
  document: DocumentRow | null
}

/**
 * The same bridge row read from an EXHIBITION (RF-516).
 *
 * A document hangs off as many artworks and shows as it speaks about, through two
 * bridge tables that differ only in which column names the other end. Everything
 * downstream — the ordering, the row the screen paints — reads the document and the
 * note and never the owner, so it is shared rather than copied.
 */
export interface ExhibitionDocumentLinkRow extends ExhibitionDocument {
  document: DocumentRow | null
}

/** The joined document, identical on both sides of the bridge. */
const LINKED_DOCUMENT_JOIN =
  'document:archive_documents(id, archive_code, artist_fund, document_type_id, title, ' +
  'archive_series_id, start_year, end_year, approximate_date, unconfirmed_date, date_note, ' +
  'date_text, physical_place_id, file_path, file_size_bytes, mime_type, uploaded_at, note, ' +
  'active, document_type:document_types(id, name, active), ' +
  'archive_series:archive_series(id, parent_id, name, active))'

export const EXHIBITION_DOCUMENT_LINK_COLUMNS =
  `id, exhibition_id, document_id, note, active, ${LINKED_DOCUMENT_JOIN}`

export const DOCUMENT_LINK_COLUMNS =
  'id, catalog_id, document_id, note, active, ' +
  'document:archive_documents(id, archive_code, artist_fund, document_type_id, title, ' +
  'archive_series_id, start_year, end_year, approximate_date, unconfirmed_date, date_note, ' +
  'date_text, physical_place_id, file_path, file_size_bytes, mime_type, uploaded_at, note, ' +
  'active, document_type:document_types(id, name, active), ' +
  'archive_series:archive_series(id, parent_id, name, active))'

/**
 * The documents oldest first, with the undated last.
 *
 * Same criterion as the bibliography and for the same reason: a letter with no
 * year is an ordinary thing in an archive, and it is not a letter from year zero.
 */
export function sortDocumentLinks<R extends { id: string; document: DocumentRow | null }>(
  rows: readonly R[],
): R[] {
  return rows.slice().sort((a, b) => {
    const ya = a.document?.start_year ?? null
    const yb = b.document?.start_year ?? null
    if (ya !== yb) {
      if (ya == null) return 1
      if (yb == null) return -1
      return ya - yb
    }
    return (
      compareText(a.document?.title ?? '', b.document?.title ?? '') || a.id.localeCompare(b.id)
    )
  })
}

// ── Related artworks (RF-217) ────────────────────────────────

/**
 * The kind of relationship, whole: its five columns are exactly what the record
 * needs, `inverse_name` included — that is the label the artwork at the OTHER end
 * shows, and it is empty exactly when the kind is symmetric.
 */
export type RelationshipTypeRef = ArtworkRelationshipType

/**
 * A relationship as it comes out of the database: one row for the pair, with
 * both artworks embedded.
 *
 * Both ends are read because the record can be on either of them: for a
 * symmetric kind the database canonicalises the pair — the smaller `catalog_id`
 * always lands in `from_catalog_id` — so «AR-0007 pareja de AR-0003» is stored as
 * one row that names AR-0003 first, and the record of AR-0007 would show nothing
 * if it only queried `from_catalog_id`.
 */
export interface RelationshipRow extends ArtworkRelationship {
  relationship_type: RelationshipTypeRef | null
  from_artwork: ArtworkRef | null
  to_artwork: ArtworkRef | null
}

const ARTWORK_REF_FIELDS = 'catalog_id, title, artist, execution_date, active'

/**
 * Both ends need an explicit foreign-key hint: `artwork_relationships` has TWO
 * foreign keys to `artworks`, and without naming which one is meant PostgREST
 * refuses the embed instead of guessing.
 */
export const RELATIONSHIP_COLUMNS =
  'id, from_catalog_id, to_catalog_id, relationship_type_id, note, active, ' +
  'relationship_type:artwork_relationship_types(id, name, inverse_name, is_symmetric, active), ' +
  `from_artwork:artworks!artwork_relationships_from_catalog_id_fkey(${ARTWORK_REF_FIELDS}), ` +
  `to_artwork:artworks!artwork_relationships_to_catalog_id_fkey(${ARTWORK_REF_FIELDS})`

/** One relationship read FROM one of its two ends. */
export interface RelationshipView {
  /** The row's identifier, unchanged: it is what an edit or a retirement acts on. */
  id: string
  /** The artwork at the other end. */
  otherCatalogId: string
  /** Null when the other record is not visible to this user, or is in the trash for a Reader. */
  other: ArtworkRef | null
  /**
   * How THIS artwork relates to the other one, in words: `name` from the near
   * end, `inverse_name` from the far one — «Estudio previo de» on one record and
   * «Obra final de» on the other, out of a single stored row.
   */
  label: string
  /** True when this record sits at the `to_` end of an asymmetric relationship. */
  reversed: boolean
  note: string
}

/**
 * A relationship as this record has to read it (RF-217).
 *
 * The direction is not decoration: the same row means two different sentences
 * depending on which record is being looked at, and getting it backwards would
 * publish the study as the finished work. A symmetric kind reads the same from
 * both ends and its `inverse_name` is empty, which is why it is checked first.
 *
 * A missing kind is not left blank. It happens when the vocabulary entry was
 * retired and a Reader cannot see it: the relationship is real, and saying that
 * its kind cannot be read is better than a row with a hole where the verb goes.
 */
export function relationshipView(row: RelationshipRow, catalogId: string): RelationshipView {
  const near = row.from_catalog_id === catalogId
  const type = row.relationship_type
  const reversed = !near && type !== null && !type.is_symmetric
  return {
    id: row.id,
    otherCatalogId: near ? row.to_catalog_id : row.from_catalog_id,
    other: near ? row.to_artwork : row.from_artwork,
    label:
      type === null
        ? 'Tipo de relación no disponible'
        : reversed
          ? type.inverse_name
          : type.name,
    reversed,
    note: row.note,
  }
}

/**
 * Every relationship of an artwork, read from its end and sorted by what the
 * cataloger sees: the kind first, then the code of the other artwork.
 *
 * Grouping by kind, and not by code, because that is how these are read — «los
 * estudios previos» is a question, «lo relacionado con AR-0042» is not.
 */
export function relationshipViews(
  rows: readonly RelationshipRow[],
  catalogId: string,
): RelationshipView[] {
  return rows
    .map((row) => relationshipView(row, catalogId))
    .sort(
      (a, b) =>
        compareText(a.label, b.label) ||
        a.otherCatalogId.localeCompare(b.otherCatalogId, 'es') ||
        a.id.localeCompare(b.id),
    )
}

// ── The documentary columns of the artwork itself ────────────

/**
 * The eight documentary columns of `artworks` (RF-218, RF-510, RF-511), with the
 * rights holder resolved.
 *
 * They are read in their own small query and not folded into `Artwork`, because
 * `Artwork` is loaded by the list, the cache and the printed record, and none of
 * those needs them. The four statuses are what every block's heading reads.
 */
export interface ArtworkDocumentaryRow extends ArtworkDocumentary {
  catalog_id: string
  rights_holder: PartyRef | null
}

export const ARTWORK_DOCUMENTARY_COLUMNS =
  'catalog_id, provenance, provenance_note, rights_holder_party_id, rights_holder_note, ' +
  'provenance_status, bibliography_status, exhibition_history_status, documentation_status, ' +
  `rights_holder:parties(${PARTY_FIELDS})`

// ── Shared ───────────────────────────────────────────────────

/**
 * es-ES comparison, accents in their place and case ignored, decided here and
 * not in the query: the database's own collation can sort «Óleo» past the z.
 */
function compareText(a: string, b: string): number {
  return a.localeCompare(b, 'es', { sensitivity: 'base' })
}
