/**
 * The Spanish the five documentary sections of the record repeat.
 *
 * Four things get written over and over across provenance, bibliography,
 * exhibition history, archive documentation and related artworks: a structured
 * date (ADR-004), the dates of an exhibition, the name of a person or an
 * institution, and the size of an uploaded file. Written once here, they read
 * the same in the five blocks; written five times they would not, and the
 * cataloger would be reading five dialects of the same catalogue.
 *
 * Everything in this module is pure and takes plain rows, so the battery — which
 * runs in node, with no DOM — can verify the sentence itself and not a component
 * that happens to contain it.
 */

import type { PartyType } from '../../lib/types'

// ── A structured date (ADR-004) ──────────────────────────────

/**
 * The four columns every dated documentary row carries, plus the text the
 * database composes out of them.
 *
 * `date_text` is a STORED GENERATED column: whoever selects it gets the
 * database's own answer and does not need the mirror below. It is optional here
 * because a form that has not saved yet has the four columns and no text.
 */
export interface StructuredDateColumns {
  start_year: number | null
  end_year: number | null
  approximate_date: boolean
  unconfirmed_date: boolean
  date_note: string
  /** Generated by the database. Read-only, and absent before saving. */
  date_text?: string | null
}

/**
 * The mirror of the `date_text` generated column of `provenance_events` and
 * `archive_documents`, for previewing a date before it is saved.
 *
 * It is NOT `composeDate` from structuredDate.ts, and the difference is one
 * character wide and deliberate: `composeDate` drops a range whose end equals
 * its start, which is right for `artworks` — its check demands
 * `end_year > start_year`, so «1978-1978» cannot exist there — and wrong here,
 * because the documentary tables check `end_year >= start_year` and the database
 * would store exactly «1978-1978». A preview that disagrees with what gets
 * stored is worse than no preview, so this one follows the SQL, verbatim,
 * including that case.
 *
 * Empty string when there is nothing: this is the composition step, and deciding
 * what an absent date reads as belongs to `displayStructuredDate`.
 */
export function structuredDateText(row: StructuredDateColumns): string {
  // The note wins whole, as it does in SQL: it is the handwriting the structure
  // could not hold («finales de los setenta»), and it is what gets published.
  if (row.date_note !== '') return row.date_note
  if (row.start_year == null) return ''
  const prefix = row.approximate_date ? 'c. ' : ''
  const range = row.end_year == null ? '' : `-${row.end_year}`
  const suffix = row.unconfirmed_date ? ' [?]' : ''
  return `${prefix}${row.start_year}${range}${suffix}`
}

/**
 * The date as the record prints it, never as a gap (RF-304).
 *
 * The database's own `date_text` is preferred whenever the query asked for it —
 * it is the published text and it cannot drift — and the mirror only covers the
 * rows that arrive without it.
 */
export function displayStructuredDate(row: StructuredDateColumns): string {
  const stored = (row.date_text ?? '').trim()
  const text = stored !== '' ? stored : structuredDateText(row).trim()
  return text === '' ? 'Sin fecha' : text
}

// ── The dates of an exhibition ───────────────────────────────

/** The four date columns of `exhibitions`. The database demands `year` or `start_date`. */
export interface ExhibitionDateColumns {
  year: number | null
  /** ISO date, `YYYY-MM-DD`. */
  start_date: string | null
  end_date: string | null
  date_note: string
}

const MONTHS = [
  'enero',
  'febrero',
  'marzo',
  'abril',
  'mayo',
  'junio',
  'julio',
  'agosto',
  'septiembre',
  'octubre',
  'noviembre',
  'diciembre',
]

interface Ymd {
  year: number
  month: number
  day: number
}

/**
 * An ISO date into its three numbers, or null when it is not one.
 *
 * Taken apart by hand and never through `new Date(...)`: an exhibition date is a
 * wall-clock day with no zone, and letting the machine's own zone touch it
 * prints the day before for anybody east of the cataloger — the same reason the
 * photograph panel formats in UTC.
 */
function splitIso(iso: string | null): Ymd | null {
  if (!iso) return null
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso)
  if (!match) return null
  const [year, month, day] = [Number(match[1]), Number(match[2]), Number(match[3])]
  if (month < 1 || month > 12 || day < 1 || day > 31) return null
  return { year, month, day }
}

/** `12 de marzo de 1985`, with the parts the caller does not need dropped. */
function dayText(date: Ymd, withMonth = true, withYear = true): string {
  const month = MONTHS[date.month - 1] ?? String(date.month)
  if (!withMonth) return String(date.day)
  return withYear ? `${date.day} de ${month} de ${date.year}` : `${date.day} de ${month}`
}

/**
 * The dates of an exhibition, in the shortest form that says everything
 * (RF-502).
 *
 * Four shapes, and the repetition is squeezed out of each one because these
 * lines sit one under another in a list and the eye reads the differences:
 *
 *   · `12-28 de marzo de 1985` — same month;
 *   · `12 de marzo – 4 de mayo de 1985` — same year;
 *   · `12 de diciembre de 1985 – 4 de enero de 1986` — across the new year;
 *   · `1985` — a bare year, which is all half the press cuttings give.
 *
 * With an opening date and no closing one, only the opening is printed. Nothing
 * is invented in either direction: the record does not claim a one-day show and
 * does not claim an open-ended one either, and whoever knows more writes it in
 * `date_note`, which is appended after a middle dot.
 */
export function exhibitionDatesText(row: ExhibitionDateColumns): string {
  const start = splitIso(row.start_date)
  const end = splitIso(row.end_date)
  const note = row.date_note.trim()

  let dates = ''
  if (start && end) {
    if (start.year !== end.year) {
      dates = `${dayText(start)} – ${dayText(end)}`
    } else if (start.month !== end.month) {
      dates = `${dayText(start, true, false)} – ${dayText(end)}`
    } else if (start.day !== end.day) {
      // An en dash and no spaces for two days of the same month: they are one
      // datum, «12-28 de marzo de 1985».
      dates = `${start.day}-${dayText(end)}`
    } else {
      dates = dayText(start)
    }
  } else if (start) {
    dates = dayText(start)
  } else if (row.year != null) {
    dates = String(row.year)
  }

  if (dates === '') return note
  return note === '' ? dates : `${dates} · ${note}`
}

/** The dates of an exhibition, never as a gap (RF-304). */
export function displayExhibitionDates(row: ExhibitionDateColumns): string {
  const text = exhibitionDatesText(row).trim()
  return text === '' ? 'Sin fechar' : text
}

/**
 * The key the exhibition history is sorted by (RF-502): the opening date, and
 * the first of January of the bare year when there is no opening date.
 *
 * It is the same `coalesce(start_date, make_date(year, 1, 1))` the database
 * indexes by, computed here because the order runs over the BRIDGE rows of one
 * artwork and PostgREST cannot order a parent by an embedded column. Null when
 * the row carries no date at all — the database forbids it, and a row that
 * arrived anyway is sorted last instead of first, where it would head the
 * history.
 */
export function exhibitionOrderKey(row: Pick<ExhibitionDateColumns, 'year' | 'start_date'>): string | null {
  if (row.start_date && /^\d{4}-\d{2}-\d{2}$/.test(row.start_date)) return row.start_date
  if (row.year == null) return null
  return `${String(row.year).padStart(4, '0')}-01-01`
}

// ── The name of a person or an institution (RF-508) ──────────

/**
 * What the record needs of a party in order to name it.
 *
 * `contact` is deliberately NOT here and is not selected by any query of this
 * feature: it is third-party personal data (RF-105), the record never prints it,
 * and the narrowest possible select is the cheapest protection there is against
 * it appearing in a screen nobody meant to put it in.
 */
export interface PartyRef {
  id: string
  party_type: PartyType
  name: string
  locality: string
  country: string
  active: boolean
}

/**
 * The name of the party, the free note when the link names nobody, and a
 * sentence when neither exists.
 *
 * `party_note` is not a fallback for a missing row: «Colección privada, España»
 * is a real, deliberate link with nobody behind it (RF-509), and the database
 * demands one of the two. «Sin identificar» is therefore the impossible case,
 * and it is written out rather than left blank because a nameless line in a
 * chain of provenance looks like a bug in the screen.
 */
export function partyName(party: PartyRef | null | undefined, note = ''): string {
  const name = party?.name.trim() ?? ''
  if (name !== '') return name
  const written = note.trim()
  return written !== '' ? written : 'Sin identificar'
}

/** `Badajoz, España`, with whichever half is missing dropped. Empty when both are. */
export function partyPlace(party: PartyRef | null | undefined): string {
  return [party?.locality.trim(), party?.country.trim()].filter((part) => part).join(', ')
}

/**
 * The party as one line: `Museo de Bellas Artes de Badajoz (Badajoz, España)`.
 *
 * The place goes in brackets and not as a second field because there is one of
 * these per row of a list on a phone, and a «Casa de Cultura» without its town
 * identifies nothing — the venues table is unique by name AND locality for that
 * very reason.
 */
export function partyText(party: PartyRef | null | undefined, note = ''): string {
  const name = partyName(party, note)
  const place = partyPlace(party)
  return place === '' ? name : `${name} (${place})`
}

// ── The size of an uploaded file ─────────────────────────────

/**
 * The size of a file, in es-ES with its decimal comma, or null when the row does
 * not say.
 *
 * This is a second implementation of `sizeText` from `archiveDownloads.ts` and
 * agrees with it to the character — there is a test that holds the two together.
 * It is copied and not imported because that module is the photograph download
 * chain: importing it drags `download.ts`, `images.ts`, `imageEdits.ts` and the
 * Supabase client into a module whose whole purpose is that it needs none of
 * them, and into every screen that shows an archive document.
 *
 * Null and not «0 KB» for a missing size: `archive_documents` writes its four
 * file columns together or not at all, so no size means no file, which is a
 * different thing from a file of no size.
 */
export function fileSizeText(bytes: number | null | undefined): string | null {
  if (typeof bytes !== 'number' || !Number.isFinite(bytes) || bytes <= 0) return null
  if (bytes < 1_048_576) return `${Math.max(1, Math.round(bytes / 1024))} KB`
  return `${(bytes / 1_048_576).toFixed(1).replace('.', ',')} MB`
}

/**
 * What the button offering a document says about its weight, never a gap.
 *
 * The size is on the control and not in a footnote for the reason RF-114 gives:
 * in a warehouse, over mobile data, «nada se descarga sin pedirlo» only means
 * something when what is being asked for says what it costs.
 */
export function displayFileSize(bytes: number | null | undefined): string {
  return fileSizeText(bytes) ?? 'Tamaño sin registrar'
}
