/**
 * What a dossier says, in order: the artworks, the free texts and the biography
 * (RF-1602, RF-1603, RF-1604, RF-1613, RF-1614, RF-1616; ADR-011).
 *
 * One list and one order, because a paragraph goes BETWEEN two artworks. So this
 * module's job is the one a single list creates: given a row of any of the three
 * kinds, say what that row shows on screen, and never let a kind fall through
 * unpainted.
 *
 * Pure. Everything that decides how an item reads is here, verified in node.
 */

import { displayDate } from '../../lib/dates'
import { displayTitle } from '../../lib/title'
import { ARTIST_LABEL, type ArtistFund, type DossierItem, type DossierItemKind } from '../../lib/types'

/**
 * The artwork as an item names it: enough to recognise it, and no more. The
 * record is one tap away and it has everything.
 */
export interface DossierArtworkRef {
  catalog_id: string
  title: string
  artist: ArtistFund
  /** Generated by the database from the structured fields (ADR-004). Read-only. */
  execution_date: string
  technique: string
  height_cm: number | null
  width_cm: number | null
  active: boolean
}

/** One row of the list: the item plus the artwork it names, when it names one. */
export interface DossierItemRow extends DossierItem {
  /**
   * Null on a TEXT or a BIOGRAPHY, and null on an ARTWORK whose record cannot be
   * read with this session — which the select policy makes impossible, but a row
   * that arrives without it is said out loud rather than painted as a blank line.
   */
  artwork: DossierArtworkRef | null
}

/**
 * The columns of the list.
 *
 * The artwork comes joined: the list of a twelve-artwork dossier would otherwise
 * be thirteen requests, and every one of the joined fields is painted — the
 * measurements included, because «92 × 73 cm» is what tells two versions of the
 * same composition apart while the order is being decided.
 *
 * Held to `DossierItemRow` by a test.
 */
export const DOSSIER_ITEM_COLUMNS =
  'id, dossier_id, kind, sort_order, catalog_id, image_id, price, currency, note, ' +
  'heading, body, artist_fund, with_cv, active, ' +
  'artwork:artworks(catalog_id, title, artist, execution_date, technique, height_cm, width_cm, active)'

/**
 * The order of the list: `sort_order`, which is the order the cataloguer put
 * them in and the order the PDF prints.
 *
 * Ties break by identifier so two items never swap places between two loads of
 * the same screen. There should be no ties among the active items —
 * `reorder_dossier_items` rewrites 1..n whole — but a withdrawn item keeps the
 * dead number it had, so two of them can share one.
 */
export function sortItems(rows: readonly DossierItemRow[]): DossierItemRow[] {
  return rows
    .slice()
    .sort((a, b) => a.sort_order - b.sort_order || a.id.localeCompare(b.id))
}

/** One item of the list, ready to paint. */
export interface DossierItemEntry {
  id: string
  kind: DossierItemKind
  /** Its place among the active items, 1..n, as the row shows it. Null for a withdrawn one, which has no place. */
  position: number | null
  /** The heading of the row: the artwork's title, the section's label, or the artist's name. */
  title: string
  /** The second line: `Rotili · 1965 · óleo sobre lienzo · 92 × 73 cm`. Never a gap. */
  subtitle: string
  /** The code, and the only link to the record (RF-604). Null when the item is not an artwork. */
  catalogId: string | null
  /** `4.500 €`, or null when this item carries no price. */
  price: string | null
  /** The paragraph of a text, or the shape of the biography block. Empty when there is none. */
  body: string
  /** The team's note, which is NOT printed (RF-1615). */
  note: string
  /** A fixed shot instead of the representative one (RF-1605). Null is «la representativa». */
  imageId: string | null
  /** Something here is in the trash, and it says which. Null when nothing is. */
  retirementNotice: string | null
  /** In the trash itself: painted greyed out. */
  retired: boolean
}

/** `92 × 73 cm`, `92 cm de alto`, or empty. Alto × ancho, which is the catalogue's convention. */
export function measurementsText(artwork: Pick<DossierArtworkRef, 'height_cm' | 'width_cm'>): string {
  const { height_cm: h, width_cm: w } = artwork
  if (h !== null && w !== null) return `${trimNumber(h)} × ${trimNumber(w)} cm`
  if (h !== null) return `${trimNumber(h)} cm de alto`
  if (w !== null) return `${trimNumber(w)} cm de ancho`
  return ''
}

/** `54.00` → `54`, `54.50` → `54,5`. The stored value carries two decimals that nobody reads aloud. */
function trimNumber(value: number): string {
  return value
    .toLocaleString('es-ES', { maximumFractionDigits: 2 })
}

/**
 * The price of an item, as it is read (RF-1604).
 *
 * `es-ES` puts the symbol after and the thousands separator as a point, which is
 * what the PDF has to print too. Null in, null out: «sin precio» is a datum and
 * this must never turn it into `0 €`, which would be a price nobody offered.
 */
export function priceText(price: number | null, currency: string): string | null {
  if (price === null) return null
  const code = currency.trim() === '' ? 'EUR' : currency.trim()
  try {
    return price.toLocaleString('es-ES', { style: 'currency', currency: code })
  } catch {
    // An unknown code would throw and take the whole list down with it. The
    // database only admits three capitals, so this is the belt to the braces.
    return `${price.toLocaleString('es-ES', { minimumFractionDigits: 2 })} ${code}`
  }
}

/**
 * What one item says.
 *
 * The `switch` over `kind` is exhaustive on purpose and the compiler is what
 * keeps it that way: the day a fourth kind is added —a page break, a full-page
 * photograph— this stops compiling instead of painting an empty row.
 */
export function itemEntry(
  row: DossierItemRow,
  options: { position: number | null; fundName?: (fund: ArtistFund) => string },
): DossierItemEntry {
  const common = {
    id: row.id,
    kind: row.kind,
    position: options.position,
    catalogId: null as string | null,
    price: null as string | null,
    body: row.body.trim(),
    note: row.note.trim(),
    imageId: row.image_id,
    retired: !row.active,
    retirementNotice: retirementNotice(row),
  }

  switch (row.kind) {
    case 'ARTWORK': {
      const artwork = row.artwork
      return {
        ...common,
        catalogId: row.catalog_id,
        title: artwork === null ? 'Obra no disponible' : displayTitle(artwork.title),
        subtitle:
          artwork === null
            ? 'La ficha de esta obra no se puede leer con tu sesión'
            : [
                ARTIST_LABEL[artwork.artist],
                displayDate(artwork.execution_date),
                artwork.technique.trim(),
                measurementsText(artwork),
              ]
                .filter((part) => part !== '')
                .join(' · '),
        price: priceText(row.price, row.currency),
      }
    }
    case 'TEXT': {
      const heading = row.heading.trim()
      return {
        ...common,
        title: heading !== '' ? heading : 'Párrafo',
        // What a text IS, said in the words of the screen and not «tipo TEXT».
        subtitle: heading !== '' ? 'Rótulo de sección' : 'Texto libre',
      }
    }
    case 'BIOGRAPHY': {
      const fund = row.artist_fund
      const name = fund === null ? '' : (options.fundName?.(fund) ?? ARTIST_LABEL[fund])
      const heading = row.heading.trim()
      return {
        ...common,
        title: heading !== '' ? heading : name !== '' ? name : 'Biografía',
        subtitle:
          row.with_cv === true ? 'Biografía y currículum' : 'Biografía, sin el currículum',
      }
    }
  }
}

/**
 * That what is being read is in the trash, said out loud.
 *
 * Two different things can be retired and they mean opposite things, so they do
 * not share a sentence: the ITEM retired means it was taken out of this dossier,
 * and the ARTWORK retired means the piece is withdrawn from the catalogue while
 * the item stands — which is RF-1613, the case the dossier deliberately does not
 * hide. The item wins when both are, because it is the row this line is about.
 */
function retirementNotice(row: DossierItemRow): string | null {
  if (!row.active) return 'Quitada de este dossier. Al añadirla otra vez vuelve con su nota y su precio.'
  if (row.artwork !== null && !row.artwork.active) {
    return 'Esta obra está retirada del catálogo: no saldrá en el PDF.'
  }
  return null
}

/**
 * The items of a dossier, in order and ready to paint.
 *
 * **Retired items are shown, greyed out and saying why**, and not dropped: a row
 * silently missing is how somebody concludes an artwork was never in the
 * dossier. The position is computed over the ACTIVE ones only, because that is
 * what `reorder_dossier_items` numbers and what the PDF prints — a withdrawn item
 * has no place in the reading and its entry says so with a null.
 */
export function itemEntries(
  rows: readonly DossierItemRow[],
  options: { fundName?: (fund: ArtistFund) => string } = {},
): DossierItemEntry[] {
  let position = 0
  return sortItems(rows).map((row) => {
    if (row.active) position += 1
    return itemEntry(row, {
      position: row.active ? position : null,
      ...(options.fundName === undefined ? {} : { fundName: options.fundName }),
    })
  })
}

/**
 * What the dossier holds, counted by kind: `12 obras · 2 textos · 1 biografía`.
 *
 * Only the active ones: it is the answer to «cuántas páginas va a tener esto»,
 * and a withdrawn item is not in the PDF. Kinds with nothing in them are absent
 * rather than written as zero — «0 textos» is noise on a phone.
 */
export function itemCountText(rows: readonly DossierItemRow[]): string {
  const live = rows.filter((row) => row.active)
  const artworks = live.filter((row) => row.kind === 'ARTWORK').length
  const texts = live.filter((row) => row.kind === 'TEXT').length
  const biographies = live.filter((row) => row.kind === 'BIOGRAPHY').length
  const parts: string[] = []
  if (artworks > 0) parts.push(artworks === 1 ? '1 obra' : `${artworks} obras`)
  if (texts > 0) parts.push(texts === 1 ? '1 texto' : `${texts} textos`)
  if (biographies > 0) parts.push(biographies === 1 ? '1 biografía' : `${biographies} biografías`)
  if (parts.length === 0) return 'Vacío'
  return parts.join(' · ')
}

/**
 * The identifiers of the active items in their current order, which is what
 * `reorder_dossier_items` takes.
 *
 * The database demands EXACTLY the active items of the dossier, so this list is
 * built from the rows the screen loaded and never from the rows it painted.
 */
export function activeOrder(rows: readonly DossierItemRow[]): string[] {
  return sortItems(rows)
    .filter((row) => row.active)
    .map((row) => row.id)
}

/**
 * The order after moving one item one place up or down, or **null when there is
 * nothing to move**.
 *
 * Null and not the unchanged list, deliberately: the caller must not spend a
 * write on a no-op, and «the first item cannot go up» is a state the button reads
 * to disable itself. The move is a swap because the list is walked with two
 * buttons and not dragged — one tap, one place, which is what works with a thumb
 * and with gloves.
 */
export function movedOrder(
  order: readonly string[],
  id: string,
  direction: 'up' | 'down',
): string[] | null {
  const from = order.indexOf(id)
  if (from === -1) return null
  const to = direction === 'up' ? from - 1 : from + 1
  if (to < 0 || to >= order.length) return null
  const next = order.slice()
  const moved = next[from]
  const displaced = next[to]
  if (moved === undefined || displaced === undefined) return null
  next[from] = displaced
  next[to] = moved
  return next
}

/**
 * What goes where the items would go, or null when there are items to paint
 * (RF-304).
 *
 * The empty dossier is the normal first state of a dossier and the sentence says
 * what to do about it, which is the only reason to write one.
 */
export function itemsNotice(state: {
  loading: boolean
  error: string | null
  count: number
}): string | null {
  if (state.error !== null) return null
  if (state.loading && state.count === 0) return 'Cargando lo que lleva este dossier…'
  if (state.count > 0) return null
  return 'Este dossier está vacío. Añade la primera obra, o el texto con el que quieras que empiece.'
}
