// Domain types, matching the database schema names: the schema is the
// project's vocabulary (see CLAUDE.md).
//
// Hand-written for now. RNF-102 plans generating them from the schema with the
// Supabase CLI (`supabase gen types typescript`), which needs the remote
// project already created. Until then, any change in a migration forces a
// change here: it is the point where schema and frontend can drift apart with
// no warning.
//
// Enum VALUES are code (the database renamed them to English via ALTER TYPE
// ... RENAME VALUE); only artist_fund keeps its values, which are surnames.
// What the user reads on screen is decided by the Spanish label maps below.

export type ArtistFund = 'ROTILI' | 'RUIZ_CAMPINS' | 'TEST'

/** Every fund, to validate values arriving from outside the code. */
export const ARTIST_FUNDS: readonly ArtistFund[] = ['ROTILI', 'RUIZ_CAMPINS', 'TEST']
export type UserRole = 'SUPERUSER' | 'CATALOGER' | 'READER'
export type TriState = 'YES' | 'NO' | 'UNREVIEWED'
export type AttributedTitleValue = 'NOT_APPLICABLE' | 'NO' | 'YES' | 'UNCONFIRMED' | 'UNREVIEWED'

export type ShotTypeValue =
  | 'GENERAL'
  | 'SIGNATURE_DETAIL'
  | 'BACK'
  | 'DAMAGE_DETAIL'
  | 'FRAME'
  | 'OTHER'

export type ConservationStatusValue =
  | 'GOOD'
  | 'FAIR'
  | 'NEEDS_RESTORATION'
  | 'NEEDS_URGENT_RESTORATION'
  | 'UNREVIEWED'

export type ExistenceStatusValue =
  | 'PRESERVED'
  | 'DESTROYED'
  | 'LOST'
  | 'UNKNOWN'
  | 'UNREVIEWED'

/**
 * One entry of the series vocabulary. The series belongs to a fund and the
 * pair is its key in `series`: each artist works in their own series.
 */
export interface SeriesEntry {
  artist: ArtistFund
  name: string
}

/**
 * One node of the tree of physical places (ADR-006).
 *
 * `parent_id` null is a root, and it is MUTABLE: hanging a place that is a root
 * today from another one tomorrow is a normal operation, and the reason the tree
 * exists. `name` is stored exactly as it is written, with its capitals and its
 * accents; what gets normalized is only the comparison key (see places.ts).
 *
 * The trash columns of the row —who retired it and when— are not here: the
 * interface only needs to know whether the place is still in use, and the rest
 * belongs to whoever audits the catalog.
 */
export interface PhysicalPlace {
  id: string
  parent_id: string | null
  name: string
  active: boolean
}

export interface Profile {
  id: string
  email: string
  name: string
  role: UserRole
}

export interface Artwork {
  catalog_id: string
  artist: ArtistFund
  title: string
  attributed_title: AttributedTitleValue
  artwork_type: string
  /** From the `series` vocabulary. Empty means the artwork belongs to none. */
  series: string
  /** Generated by the database from the structured fields. Read-only. */
  execution_date: string
  start_year: number | null
  end_year: number | null
  approximate_date: boolean
  unconfirmed_date: boolean
  date_note: string
  technique: string
  support: string
  height_cm: number | null
  width_cm: number | null
  depth_cm: number | null
  signed: TriState
  signature_description: string
  dated_on_artwork: TriState
  conservation_status: ConservationStatusValue
  /**
   * Where the artwork is: a node of `physical_places` (ADR-006). Null is
   * legitimate — cataloging with the piece in front of you cannot demand
   * deciding where it is.
   */
  physical_place_id: string | null
  // `physical_location`, the old location as text with the notation convention
  // of field schema v11, is deliberately NOT here. The column still exists —
  // it is retired in a later deployment, after this frontend is the only one
  // running — but nothing reads or writes it any more, and a field no query
  // selects is a trap: whoever read it would get undefined, with the type
  // promising a string. It is `not null default ''`, so an insert that leaves
  // it out is fine.
  existence_status: ExistenceStatusValue
  photographed: boolean
  measurements_verified: boolean
  inventory_phase_completed: boolean
  documentation_phase_completed: boolean
  catalog_record_complete: boolean
  inventory_process_notes: string
  updated_at: string
  basic_updated_at: string | null
  updated_by: string | null
  active: boolean
}

/** The minimum the quick capture needs to create a record (RF-1204). */
export type NewArtwork = Pick<Artwork, 'artist'> & Partial<Omit<Artwork, 'artist'>>

// ── Interface labels ─────────────────────────────────────────
// The stored value is a stable code; what gets read on screen is decided here.
// This way, renaming a label never forces a data migration. Labels stay in
// Spanish: it is the users' language.

export const ARTIST_LABEL: Record<ArtistFund, string> = {
  ROTILI: 'Alberto Rotili',
  RUIZ_CAMPINS: 'María Ruiz Campins',
  // Rehearsal fund (TS- series): test records, never real artwork.
  TEST: 'Pruebas',
}

export const ROLE_LABEL: Record<UserRole, string> = {
  SUPERUSER: 'Superusuario',
  CATALOGER: 'Catalogador',
  READER: 'Lector · solo consulta',
}

export const TRI_STATE_LABEL: Record<TriState, string> = {
  YES: 'Sí',
  NO: 'No',
  UNREVIEWED: 'Sin revisar',
}

export const ATTRIBUTED_TITLE_LABEL: Record<AttributedTitleValue, string> = {
  NOT_APPLICABLE: 'No consta título',
  NO: 'Del artista',
  YES: 'Atribuido',
  UNCONFIRMED: 'Sin confirmar',
  UNREVIEWED: 'Sin revisar',
}

/**
 * The five states split by whether a title is written (RF-209): with a blank
 * field only UNREVIEWED and NOT_APPLICABLE apply; with a written title, the
 * other three. The database enforces it (artworks_attributed_title_matches_title).
 */
export const ATTRIBUTED_TITLE_DESCRIPTION: Record<AttributedTitleValue, string> = {
  NO: 'Título auténtico, puesto por el artista',
  YES: 'Nombre de conveniencia de terceros (familia, comisario…)',
  UNCONFIRMED: 'Hay título, pero no está verificado si es del artista o atribuido',
  NOT_APPLICABLE: 'La investigación ha verificado que la obra no tiene título',
  UNREVIEWED: 'Pendiente de investigar; la ficha muestra [Sin título]',
}

export const CONSERVATION_LABEL: Record<ConservationStatusValue, string> = {
  GOOD: 'Bueno',
  FAIR: 'Regular',
  NEEDS_RESTORATION: 'Requiere restauración',
  NEEDS_URGENT_RESTORATION: 'Requiere restauración urgente',
  UNREVIEWED: 'Sin revisar',
}

export const EXISTENCE_LABEL: Record<ExistenceStatusValue, string> = {
  PRESERVED: 'Conservada',
  DESTROYED: 'Destruida',
  LOST: 'Perdida (paradero desconocido)',
  UNKNOWN: 'Estado desconocido',
  UNREVIEWED: 'Sin revisar',
}

// The artwork types (RF-213) are no longer a hardcoded list here: they live
// in the `artwork_types` table — an open vocabulary catalogers extend from
// the forms (see useArtworkTypes).

/**
 * Photographic shot types. A short list on purpose: during capture one must be
 * able to choose with a single tap, and the schema leaves it open with "Otro"
 * for whatever does not fit, instead of forcing the full taxonomy upfront.
 */
export const SHOT_TYPE_LABEL: Record<ShotTypeValue, string> = {
  GENERAL: 'General',
  SIGNATURE_DETAIL: 'Firma',
  BACK: 'Reverso',
  DAMAGE_DETAIL: 'Daño',
  FRAME: 'Marco',
  OTHER: 'Otro',
}
