// Domain types, matching the database schema names: the schema is the
// project's vocabulary (see CLAUDE.md).
//
// Hand-written for now. RNF-102 plans generating them from the schema with the
// Supabase CLI (`supabase gen types typescript`), which needs the remote
// project already created. Until then, any change in a migration forces a
// change here: it is the point where schema and frontend can drift apart with
// no warning.
//
// Enum VALUES stay as persisted in the database ('ROTILI', 'SIN_REVISAR'...):
// they are data, not code. What the user reads on screen is decided by the
// label maps below.

export type ArtistFund = 'ROTILI' | 'RUIZ_CAMPINS' | 'TEST'

/** Every fund, to validate values arriving from outside the code. */
export const ARTIST_FUNDS: readonly ArtistFund[] = ['ROTILI', 'RUIZ_CAMPINS', 'TEST']
export type UserRole = 'SUPERUSUARIO' | 'CATALOGADOR' | 'LECTOR'
export type TriState = 'SI' | 'NO' | 'SIN_REVISAR'
export type AttributedTitleValue = 'NO_APLICA' | 'NO' | 'SI' | 'SIN_REVISAR'

export type ShotTypeValue =
  | 'GENERAL'
  | 'DETALLE_FIRMA'
  | 'REVERSO'
  | 'DETALLE_DANO'
  | 'MARCO'
  | 'OTRO'

export type ConservationStatusValue =
  | 'BUENO'
  | 'REGULAR'
  | 'REQUIERE_RESTAURACION'
  | 'REQUIERE_RESTAURACION_URGENTE'
  | 'SIN_REVISAR'

export type ExistenceStatusValue =
  | 'CONSERVADA'
  | 'DESTRUIDA'
  | 'PERDIDA'
  | 'DESCONOCIDO'
  | 'SIN_REVISAR'

export interface Profile {
  id: string
  email: string
  name: string
  role: UserRole
}

export interface Artwork {
  catalog_id: string
  artist: ArtistFund
  title: string
  attributed_title: AttributedTitleValue
  artwork_type: string
  /** Generated by the database from the structured fields. Read-only. */
  execution_date: string
  start_year: number | null
  end_year: number | null
  approximate_date: boolean
  unconfirmed_date: boolean
  date_note: string
  technique: string
  support: string
  height_cm: number | null
  width_cm: number | null
  depth_cm: number | null
  signed: TriState
  signature_description: string
  dated_on_artwork: TriState
  conservation_status: ConservationStatusValue
  physical_location: string
  existence_status: ExistenceStatusValue
  photographed: boolean
  measurements_verified: boolean
  inventory_phase_completed: boolean
  documentation_phase_completed: boolean
  catalog_record_complete: boolean
  inventory_process_notes: string
  updated_at: string
  basic_updated_at: string | null
  updated_by: string | null
  active: boolean
}

/** The minimum the quick capture needs to create a record (RF-1204). */
export type NewArtwork = Pick<Artwork, 'artist'> & Partial<Omit<Artwork, 'artist'>>

// ── Interface labels ─────────────────────────────────────────
// The stored value is a stable code; what gets read on screen is decided here.
// This way, renaming a label never forces a data migration. Labels stay in
// Spanish: it is the users' language.

export const ARTIST_LABEL: Record<ArtistFund, string> = {
  ROTILI: 'Alberto Rotili',
  RUIZ_CAMPINS: 'María Ruiz Campins',
  // Rehearsal fund (TS- series): test records, never real artwork.
  TEST: 'Pruebas',
}

export const ROLE_LABEL: Record<UserRole, string> = {
  SUPERUSUARIO: 'Superusuario',
  CATALOGADOR: 'Catalogador',
  LECTOR: 'Lector · solo consulta',
}

export const TRI_STATE_LABEL: Record<TriState, string> = {
  SI: 'Sí',
  NO: 'No',
  SIN_REVISAR: 'Sin revisar',
}

export const ATTRIBUTED_TITLE_LABEL: Record<AttributedTitleValue, string> = {
  NO_APLICA: 'No aplica (sin título)',
  NO: 'No, es título del artista',
  SI: 'Sí, nombre de conveniencia',
  SIN_REVISAR: 'Sin revisar',
}

export const CONSERVATION_LABEL: Record<ConservationStatusValue, string> = {
  BUENO: 'Bueno',
  REGULAR: 'Regular',
  REQUIERE_RESTAURACION: 'Requiere restauración',
  REQUIERE_RESTAURACION_URGENTE: 'Requiere restauración urgente',
  SIN_REVISAR: 'Sin revisar',
}

export const EXISTENCE_LABEL: Record<ExistenceStatusValue, string> = {
  CONSERVADA: 'Conservada',
  DESTRUIDA: 'Destruida',
  PERDIDA: 'Perdida (paradero desconocido)',
  DESCONOCIDO: 'Estado desconocido',
  SIN_REVISAR: 'Sin revisar',
}

/**
 * Open list of artwork types (RF-213 and field schema v11): suggestions, not a
 * closed set. The field is free text and accepts any new value with no
 * migration.
 */
export const SUGGESTED_ARTWORK_TYPES = [
  'Pintura',
  'Dibujo',
  'Escultura',
  'Collage',
  'Grabado',
  'Técnica mixta',
]

/**
 * Photographic shot types. A short list on purpose: during capture one must be
 * able to choose with a single tap, and the schema leaves it open with "Otro"
 * for whatever does not fit, instead of forcing the full taxonomy upfront.
 */
export const SHOT_TYPE_LABEL: Record<ShotTypeValue, string> = {
  GENERAL: 'General',
  DETALLE_FIRMA: 'Firma',
  REVERSO: 'Reverso',
  DETALLE_DANO: 'Daño',
  MARCO: 'Marco',
  OTRO: 'Otro',
}
